export const GET_STUDENT = 'GET_STUDENT';
export const CREATE_NEW_STUDENT = 'CREATE_NEW_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const UPDATE_STUDENT_DETAILS = "UPDATE_STUDENT_DETAILS";
export const GET_STUDENT_DETAILS = "GET_STUDENT_DETAILS"
export const GET_FAMILY_MEMBERS = 'GET_FAMILY_MEMBERS';
export const UPDATE_FAMILT_MEMBER = 'UPDATE_FAMILT_MEMBER';
export const DELETE_FAMILT_MEMBER = 'DELETE_FAMILT_MEMBER';
export const GET_FAMILY_MEMBER_NATIONALITY = "GET_FAMILY_MEMBER_NATIONALITY";
export const UPDATE_FAMILY_MEMBER_NATIONALITY = "UPDATE_FAMILY_MEMBER_NATIONALITY";
export const GET_ALL_NATIONALITY = 'GET_ALL_NATIONALITY';
export const GET_ALL_SUBMITTEDSTUDENT = 'GET_ALL_SUBMITTEDSTUDENT';
export const CURRENT_ROLE = 'CURRENT_ROLE';
export const REGISTER_STUDENT_APPROVAL = 'REGISTER_STUDENT_APPROVAL'
export const GET_CURRENT_STUDENT_NATIONALITY = 'GET_CURRENT_STUDENT_NATIONALITY';

